# Generated by Django 4.1.6 on 2023-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradinghelper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingstrategyrecord',
            name='number_of_trades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingstrategyrecord',
            name='number_of_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradingstrategyrecord',
            name='total_benefit',
            field=models.FloatField(default=0),
        ),
    ]
