# Generated by Django 4.1.6 on 2023-03-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradinghelper', '0003_rsirecord_delete_tradingstrategyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=10)),
                ('benefit', models.FloatField(default=0)),
                ('params', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RSIRecord',
        ),
    ]
